apiVersion: apps/v1
kind: Deployment

metadata:
  name: patient-db

spec:
  replicas: {{ .Values.database.replicas }}

  selector:
    matchLabels:
      app: patient-db

  template:
    metadata:
      labels:
        app: patient-db

    spec:
      containers:
      - name: patient-db
        image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"

        ports:
        - containerPort: {{ .Values.database.containerPort }}

        env:
        - name: ACCEPT_EULA
          value: "Y"

        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: patient-db-secret
              key: MSSQL_SA_PASSWORD