apiVersion: v1
kind: Service

metadata:
  name: patient-ui-service

spec:
  selector:
    app: patient-ui

  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: {{ .Values.ui.service.targetPort }}

  type: {{ .Values.ui.service.type }}