# Default values for the Patient Monitoring Helm chart.

api:
  replicas: 1

  image:
    repository: patient-api
    tag: latest

  containerPort: 8000
  
  service:
    port: 8000
    targetPort: 8000